import { chromium } from "playwright";
const out = process.argv[2];
const b = await chromium.launch(); const p = await b.newPage({ viewport: { width: 1440, height: 1000 } });
const errs = []; p.on("console", m => { if (["error","warning"].includes(m.type())) errs.push(`${m.type()}: ${m.text()}`); }); p.on("pageerror", e => errs.push("pageerror: " + e.message));
await p.goto("http://127.0.0.1:8080/#/playground"); await p.waitForTimeout(1500);
for (const name of ["Laya · English", "Decider 0.8B", "Word-overlap baseline"]) await p.getByRole("button", { name, exact: true }).click();
await p.getByRole("button", { name: /^Run/ }).click();
await p.getByText("Raw responses").waitFor({ timeout: 30000 }); await p.waitForTimeout(500);
await p.screenshot({ path: `${out}/flow-playground.png`, fullPage: true });
await p.getByLabel("Load a preset").selectOption({ label: "Long contract (truncation trap)" });
await p.getByRole("button", { name: /^Run/ }).click(); await p.waitForTimeout(3000);
await p.screenshot({ path: `${out}/flow-truncation.png`, fullPage: true });
await p.goto("http://127.0.0.1:8080/#/bench"); await p.waitForTimeout(1200);
for (const name of ["Laya · English", "Decider 0.8B", "Word-overlap baseline"]) await p.getByRole("button", { name, exact: true }).click();
await p.getByRole("button", { name: "50", exact: true }).click();
await p.getByRole("button", { name: "Run benchmark" }).click();
await p.getByText("Leaderboard").waitFor({ timeout: 300000 });
await p.waitForFunction(() => !document.querySelector(".pill.busy") || !document.body.innerText.includes("running"), null, { timeout: 300000 }).catch(()=>{});
await p.waitForTimeout(90000);
await p.screenshot({ path: `${out}/flow-bench.png`, fullPage: true });
await p.goto("http://127.0.0.1:8080/#/load"); await p.waitForTimeout(1200);
await p.getByLabel("Engine").selectOption({ index: 1 });
await p.getByRole("button", { name: "Run load test" }).click();
await p.getByText("Peak throughput").waitFor({ timeout: 300000 }); await p.waitForTimeout(60000);
await p.screenshot({ path: `${out}/flow-load.png`, fullPage: true });
await p.goto("http://127.0.0.1:8080/#/runs"); await p.waitForTimeout(1500);
await p.screenshot({ path: `${out}/flow-runs.png`, fullPage: true });
console.log(JSON.stringify(errs, null, 1)); await b.close();
